[project]
name = "project-scraper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openpyxl>=3.1.5",
    "streamlit>=1.48.1",
    "watchdog>=6.0.0",
]
